package helloworld.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class ForEachStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public ForEachStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "helloworld.structure.ForEachStatement";
  }
}
