package matrix.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 1:
        return new MatrixLiteral_BehaviorDescriptor();
      case 2:
        return new MatrixLiteralCol_BehaviorDescriptor();
      case 4:
        return new VectorType_BehaviorDescriptor();
      case 3:
        return new MatrixType_BehaviorDescriptor();
      case 0:
        return new CrossProductExpression_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"matrix.structure.CrossProductExpression", "matrix.structure.MatrixLiteral", "matrix.structure.MatrixLiteralCol", "matrix.structure.MatrixType", "matrix.structure.VectorType"};
}
