package matrix.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.BinaryArithmeticExpression_BehaviorDescriptor;

public class CrossProductExpression_BehaviorDescriptor extends BinaryArithmeticExpression_BehaviorDescriptor {
  public CrossProductExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "matrix.structure.CrossProductExpression";
  }
}
