package matrix.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class IMatrixType_Behavior {
  public static void init(SNode thisNode) {
  }

  @Deprecated
  public static SNode call_cloneForBaseType_4136649939484582416(SNode thisNode, SNode baseType) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), thisNode, "virtual_cloneForBaseType_4136649939484582416", new Object[]{baseType});
  }

  @Deprecated
  public static SNode callSuper_cloneForBaseType_4136649939484582416(SNode thisNode, String callerConceptFqName, SNode baseType) {
    return BehaviorManager.getInstance().invokeSuper((Class<SNode>) ((Class) Object.class), SNodeOperations.cast(thisNode, "matrix.structure.IMatrixType"), callerConceptFqName, "virtual_cloneForBaseType_4136649939484582416", new Class[]{SNode.class, SNode.class}, new Object[]{baseType});
  }
}
