package matrix.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface IMatrixType_BehaviorDescriptor {
  public SNode virtual_cloneForBaseType_4136649939484582416(SNode thisNode, SNode baseType);
}
