package matrix.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Literal_BehaviorDescriptor;

public class MatrixLiteral_BehaviorDescriptor extends Literal_BehaviorDescriptor {
  public MatrixLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "matrix.structure.MatrixLiteral";
  }
}
