package matrix.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class MatrixLiteralCol_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public MatrixLiteralCol_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "matrix.structure.MatrixLiteralCol";
  }
}
